### PR TITLE
fix: filecheck error when not file submitted

### PR DESCRIPTION
**Pull request by ccarruitero**
fix https://github.com/workshopper/workshopper-adventure/issues/71

### CODE REVIEW

**Comment by ccarruitero** [comment]
cc @martinheidegger

**Comment by ccarruitero** [comment]
Thanks @martinheidegger for the review. 

I think your suggestions are reasonable. I'll update the PR according that.

**Comment by ccarruitero** [comment]
@martinheidegger I updated the PR. I refactored the other error too, so we need to set the binding just in one place. Take a look when you have a chance.

**Comment by martinheidegger** [comment]
Released as 3.0.2 (also added standard linting and standard-release)

**Pull request merged**
